name: Despliegue producción
on:   
  push:
    branches:
      - main

jobs:
  despliegue-pre:
    environment: produccion
    name: Despliegue producción
    env:
      SF_INSTANCE_URL: ${{ secrets.SALESFORCE_URL }} 
      SF_INSTANCE_ALIAS: ${{ secrets.SALESFORCE_ALIAS }} 
      SF_CLIENT_ID: ${{ secrets.SALESFORCE_CLIENT_ID }} 
      SF_USERNAME: ${{ secrets.SALESFORCE_USER }} 
      SF_JWT: ${{ secrets.SALESFORCE_JWT }} 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run despliegue a producción
        uses: TFM-UOC-JMGS-Ciberseguridad/tfm/docker-actions/despliegue-produccion@main
