name: Recordatorio DAST
on: 
 pull_request:
    branches:
     - main
     - preproduccion

jobs:
  recordatorio-dast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Recuerda realizar el análisis DAST con ZAP después del despliegue sobre el entorno de Salesforce.'
            })
